version: 1
services:
- type: web
  name: ghcr-badge
  runtime: docker
  repo: https://github.com/fredbi/ghcr-badge
  plan: free
  region: frankfurt
  healthCheckPath: /health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  domains:
  - ghcr-badge.swagger.dev
